export const BASE_PROPERTIES_ACTIONS = Object.freeze({
    UPDATE_BASE_PROPERTIES: "UPDATE_BASE_PROPERTIES",
    INIT_BASE_PROPERTIES: "INIT_BASE_PROPERTIES",
    REMOVE_BASE_PROPERTIES: "REMOVE_BASE_PROPERTIES",
    IMPORT_BASE_PROPERTIES: "IMPORT_BASE_PROPERTIES"
});
