export const ENTITY_TYPES_LIST_ACTIONS = Object.freeze({
    INIT_ENTITY: "INIT_ENTITY",
    REMOVE_ENTITY: "REMOVE_ENTITY",
    IMPORT_ENTITY_DATA: "IMPORT_ENTITY_DATA",

    // I haven't decided if the editor will support some extra COMPONENTS like collision  box or mask etc
    // ADD_EXTRA_ENTITY_COMPONENTS: "ADD_EXTRA_ENTITY_COMPONENTS",
    // REMOVE_EXTRA_ENTITY_COMPONENTS: "REMOVE_EXTRA_ENTITY_COMPONENTS",
});
