export const SPRITE_PROPERTIES_ACTIONS = Object.freeze({
    UPDATE_SPRITE_PROPERTIES: "UPDATE_SPRITE_PROPERTIES",
    INIT_SPRITE_PROPERTIES: "INIT_SPRITE_PROPERTIES",
    REMOVE_SPRITE_PROPERTIES: "REMOVE_SPRITE_PROPERTIES",
    IMPORT_SPRITE_PROPERTIES: "IMPORT_SPRITE_PROPERTIES",
});
