export const TEXT_PROPERTIES_ACTIONS = Object.freeze({
    UPDATE_TEXT_PROPERTIES: "UPDATE_TEXT_PROPERTIES",
    INIT_TEXT_PROPERTIES: "INIT_TEXT_PROPERTIES",
    REMOVE_TEXT_PROPERTIES: "REMOVE_TEXT_PROPERTIES",
    IMPORT_TEXT_PROPERTIES: "IMPORT_TEXT_PROPERTIES",
});
