export const NINE_SLICE_SPRITE_PROPERTIES_ACTIONS = Object.freeze({
    UPDATE_NINE_SLICE_SPRITE_PROPERTIES: "UPDATE_NINE_SLICE_SPRITE_PROPERTIES",
    INIT_NINE_SLICE_SPRITE_PROPERTIES: "INIT_NINE_SLICE_SPRITE_PROPERTIES",
    REMOVE_NINE_SLICE_SPRITE_PROPERTIES: "REMOVE_NINE_SLICE_SPRITE_PROPERTIES",
    IMPORT_NINE_SLICE_SPRITE_PROPERTIES: "IMPORT_NINE_SLICE_SPRITE_PROPERTIES",
});
