export const NODE_PROPERTIES_LIST_ACTIONS = Object.freeze({
    INIT_NODE_PROPERTIES: "INIT_NODE_PROPERTIES",
    ADD_NODE_PROPERTY: "ADD_NODE_PROPERTY",
    REMOVE_NODE_PROPERTY: "REMOVE_NODE_PROPERTY"
});
