export const GRAPHICS_PROPERTIES_ACTIONS = Object.freeze({
    UPDATE_GRAPHICS_PROPERTIES: "UPDATE_GRAPHICS_PROPERTIES",
    INIT_GRAPHICS_PROPERTIES: "INIT_GRAPHICS_PROPERTIES",
    REMOVE_GRAPHICS_PROPERTIES: "REMOVE_GRAPHICS_PROPERTIES",
    IMPORT_GRAPHICS_PROPERTIES: "IMPORT_GRAPHICS_PROPERTIES"
});
